# Numpy Indexing of 1d array

In [1]:
import numpy as np

In [2]:
# Create an array of integers from 0 to 10
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [3]:
# Call element under index n using array[n]
arr[8]

8

In [4]:
# Call elements under indexes in a range from (a) to (b excluding) using array[a:b]
arr[1:5]

array([1, 2, 3, 4])

In [5]:
# We can remove start point or stop point to call all of the element from some point or until some point
# Remember that indexing starts at 0!
print(arr[5:])
print(arr[:6])

[ 5  6  7  8  9 10]
[0 1 2 3 4 5]


In [6]:
# Also NumPy arrays are able to broadcast 
arr[0:5] = 100
print(arr)


[100 100 100 100 100   5   6   7   8   9  10]


In [7]:
# We can slice arrays
slice_of_arr = arr[0:6]
print(slice_of_arr)

[100 100 100 100 100   5]


In [8]:
# We can broadcast in bot directions with the same logic as calling array
slice_of_arr[:5] = 99
print(slice_of_arr)
slice_of_arr[3:] = 100
print(slice_of_arr)

[99 99 99 99 99  5]
[ 99  99  99 100 100 100]


In [9]:
# Copy array using array.copy
arr_copy = arr.copy()
print(arr_copy, arr)
# Check if copying is done right
arr_copy[:] = 100
print(arr_copy, arr)

[ 99  99  99 100 100 100   6   7   8   9  10] [ 99  99  99 100 100 100   6   7   8   9  10]
[100 100 100 100 100 100 100 100 100 100 100] [ 99  99  99 100 100 100   6   7   8   9  10]
