# NumPy Arrays

In [1]:
import numpy as np

In [2]:
#basic matrix creation as list of lists
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [3]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
#use np.arange(start, stop, step) to generate an array
np.arange(0,10) #indexing from 0, excluding 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(2,11,2) #get even numbers until 10

array([ 2,  4,  6,  8, 10])

In [6]:
#generate 1*3 array of zeros
np.zeros(3)

array([0., 0., 0.])

In [7]:
#generate 2*3 array of ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
#generate a number(c) of evenly spaced points from (a) to (b) 
#using np.linspace(a,b,c)
#for example 6 evenly spaced points from 1 to 10
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [9]:
#create n-dimensional identity matrix (basis matrix) using np.eye(n)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
#create one-dimensional array of n numbers using np.random.rand(n)
np.random.rand(7)

array([0.17978245, 0.93235343, 0.71749763, 0.04337742, 0.54565702,
       0.10818766, 0.19078564])

In [11]:
#create x by y array of random numbers using np.random.rand(x,y)
np.random.rand(5,5)

array([[0.63558704, 0.10982205, 0.56074925, 0.50195126, 0.03529551],
       [0.26300048, 0.4584314 , 0.01487956, 0.06848593, 0.70758307],
       [0.2687178 , 0.08758014, 0.75578478, 0.55383937, 0.98166867],
       [0.51132442, 0.09013847, 0.98026385, 0.15372953, 0.10435417],
       [0.21857068, 0.79087165, 0.37775455, 0.73638605, 0.15395283]])

In [12]:
#create an array of n random normally ditributed numbers according to 0 using
#using np.random.randn(n)
np.random.randn(9)

array([ 0.40331096,  0.30349852, -1.06119893,  0.67315835,  1.66513312,
       -1.11873556, -0.15619029, -0.13344269,  0.38178074])

In [13]:
#create x by y dimensional array of random normally distributed numbers according to 0
#using np.random.randn(x,y)
np.random.randn(3,3)

array([[ 1.24300251,  0.35341428, -0.02613453],
       [-0.95176257,  0.27551758,  0.83789167],
       [ 0.04156358, -0.45068146, -1.74241202]])

In [14]:
#create an array of length (c) of random integers from (a) to (b)
#using np.random.randint(a,b,c)
np.random.randint(1,1000,42)

array([230, 379, 874, 661,   4, 543, 969, 345, 466,  26, 635, 486, 270,
       318, 799, 374, 348, 952, 711,  90, 459,  78, 433, 348, 566, 248,
        68, 974, 854, 868, 398, 339, 239, 940, 274, 796, 181, 173, 241,
       536, 640,  20])

In [15]:
#reshape an array using .reshape
#reshaped array must remain with the same number of elements
arr = np.arange(25)
print(arr)
arr.reshape(5,5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
#get random array of 10 integers from 0 to 50
ranarr = np.random.randint(0,50,10)
print(ranarr)
#return max value of an array
print(ranarr.max())
#return min value of an array
print(ranarr.min())

[ 5 19 35 31 48  4  4 46 31 44]
48
4


In [17]:
#get the location of max or min values (indexing starts from 0!)
print(ranarr)
print(ranarr.argmax())
print(ranarr.argmin())

[ 5 19 35 31 48  4  4 46 31 44]
4
5


In [18]:
#get the shape of an array
arr.shape

(25,)

In [19]:
#get datatype of the array
arr.dtype

dtype('int64')